#!/usr/bin/python
"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

"""
from math import sqrt

def diviseur(n):
    divi = 0
    racine = int(sqrt(n))
    for i in range(1,racine+1):
            if n%i == 0:
                    divi += 1
    return 2*divi

def suite():
    a = 1
    b = 2
    while diviseur(a) <= 500:
            a += b
            b += 1
    return a

print(suite())
